spring:
  profiles : default
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username : plateer
        password: 1234
        url: jdbc:mysql://localhost:3306/market?characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
        
#  datasource :
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: plateer
#    password : 1234
#    url : jdbc:mariadb://localhost:3306/market

token :
  secretKey : homemarket
  

mybatis:
  type-aliases-package: com.plateer.homemarket
  mapper-locations: mapper/*.xml
  